# see https://compose-spec.io/
version: '3.7'
services:
  frontend:
    restart: no
    pull_policy: always
    image: ghcr.io/updraft0/controltower-fe:latest
    ports:
      - "8091:8080"
    volumes:
      - ./ui/nginx.conf:/etc/nginx/nginx.conf:ro
    # - /path/to/ssl.key:/etc/ssl/your.fqdn.here.key:ro
    # - /path/to/ssl.pem:/etc/ssl/your.fqdn.here.pem:ro
    depends_on:
      backend:
        condition: service_healthy
  backend:
    restart: no
    pull_policy: always
    image: ghcr.io/updraft0/controltower:latest
    env_file:
      - ./secret.env
    environment:
      - CT_HTTP_UI_PORT=8091
      - JAVA_OPTS=-Xmx4G -XX:+UseZGC
      - SDE_PARALLEL=1
    # - CT_HTTP_PROTO=https
    # - CT_HTTP_HOST=your.fqdn.here
    # - CT_HTTP_UI_PORT=8443
    volumes:
     - ./ctdb:/app/db
    ports:
      - "8092:8092"
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8092/api/reference/version"]
      interval: 10s
      timeout: 5s
      retries: 3
