## Auth requests
##
## These requests are used for authorization

###

# Get authorization config such as server hostname, and parameters for the oauth2 callback.
# Also sets the session cookie if one is not present.
# @name GetAuthUser
GET {{api}}/user/info
Cookie: CT-Session={{ctsessionid}}

###


# Use this to test updating user preferences
# @name UpdatePreferences
PUT {{api}}/user/preferences
Cookie: CT-Session={{ctsessionid}}
Content-Type: application/json

{
  "map": {
    "click_resets_selection": true
  },
  "sig": {
    "replace_signatures_by_default": true
  }
}

###


# Use this debug the login CORS/secure cookie auth flow
# @no-redirect
# @no-cookie-jar
# @name DebugLogin
GET {{api}}/auth/login

