## Auth requests
##
## These requests are used for authorization

###

# Get authorization config such as server hostname, and parameters for the oauth2 callback.
# Also sets the session cookie if one is not present.
# @name GetAuthUser
GET {{api}}/user/info
Cookie: __Host-CT-Session={{ctsessionid}}

###

