## Map requests
##
## Create and manipulate maps

# Create a new map with the given map policy
# @name CreateNewMap
< {%
    request.variables.set("name", "examplemap")
%}
POST {{api}}/map
Content-Type: application/json
Cookie: CT-Session={{ctsessionid}}

{
  "name": "{{name}}",
  "policy_members": [
    {
      "member_id": {{characterId}},
      "member_type": "Character",
      "is_deny": false,
      "role": "Admin"
    }
  ],
  "display_type": "Manual"
}

###
@characterName = Updraft0

# Main map WebSocket through which the UI talks in a bidirectional message stream
# @name MapWebsocket
< {%
    request.variables.set("name", "examplemap")
%}
WEBSOCKET {{apiws}}/map/ws/{{name}}/{{characterName}}
Content-Type: application/json
Cookie: CT-Session={{ctsessionid}}

# 1. get map snapshot
# 2. add jita
# 3. set coordinates
# 4. remove jita again
# 5. readd jita by updating coordinates
# 6. add amarr
# 7. add rens
# 8. add dodixie
# 9. add shattered wh system with name ABC-12

===

"GetSnapshot"

===

{
  "AddSystem": {
    "system_id": 30000142,
    "is_pinned": true,
    "display_data": {
      "Manual": {
        "x": 0,
        "y": 0
      }
    },
    "stance": "Unknown"
  }
}

===

{
  "UpdateSystem": {
    "system_id": 30000142,
    "display_data": {"Manual": {"x": 20, "y": 0}}
  }
}

===

{
  "RemoveSystem": {
    "system_id": 30000142
  }
}

===

{
  "UpdateSystem": {
    "system_id": 30000142,
    "display_data": {"Manual": {"x": 50, "y": 50}}
  }
}

===

{
  "AddSystem": {
    "system_id": 30002187,
    "is_pinned": true,
    "display_data": {"Manual": {"x": 90, "y": 40}},
    "stance": "Unknown"
  }
}

===

{
  "AddSystem": {
    "system_id": 30002659,
    "is_pinned": true,
    "display_data": {"Manual": {"x": 90, "y": 200}},
    "stance": "Unknown"
  }
}

===

{
  "AddSystem": {
    "system_id": 30002510,
    "is_pinned": true,
    "display_data": {"Manual": {"x": 90, "y": 240}},
    "stance": "Unknown"
  }
}

===

{
  "AddSystem": {
    "system_id": 31002558,
    "name": {
      "Some": {
        "value": "ABC-12"
      }
    },
    "is_pinned": true,
    "display_data": {"Manual": {"x": 240, "y": 240}},
    "stance": "Friendly"
  }
}

===

{
  "AddSystemConnection": {
    "from_system_id": 30002510,
    "to_system_id": 31002558
  }
}

###
