## Map requests
##
## Create and manipulate maps

# Create a new map with the given map policy
# @name CreateNewMap
< {%
    request.variables.set("name", "examplemap")
%}
POST {{api}}/map
Content-Type: application/json
Cookie: __Host-CT-Session={{ctsessionid}}

{
  "name": "{{name}}",
  "policyMembers": [
    {
      "memberId": {{characterId}},
      "memberType": "Character",
      "isDeny": false,
      "role": "Admin"
    }
  ],
  "displayType": "Manual"
}

###

# Main map WebSocket through which the UI talks in a bidirectional message stream
# @name MapWebsocket
< {%
    request.variables.set("name", "examplemap")
%}
WEBSOCKET {{apiws}}/map/{{name}}/{{characterId}}/ws
Content-Type: application/json
Cookie: __Host-CT-Session={{ctsessionid}}

# 1. get map snapshot
# 2. add jita
# 3. set coordinates
# 4. remove jita again
# 5. readd jita by updating coordinates
# 6. add amarr
# 7. add rens
# 8. add dodixie
# 9. add shattered wh system with name ABC-12

===

{"GetSnapshot":  {}}

===

{
  "AddSystem": {
    "systemId": 30000142,
    "isPinned": true,
    "displayData": {
      "Manual": {
        "x": 0,
        "y": 0
      }
    },
    "stance": "Unknown"
  }
}

===

{
  "UpdateSystem": {
    "systemId": 30000142,
    "displayData": {"Manual": {"x": 20, "y": 0}}
  }
}

===

{
  "RemoveSystem": {
    "systemId": 30000142
  }
}

===

{
  "UpdateSystem": {
    "systemId": 30000142,
    "displayData": {"Manual": {"x": 50, "y": 50}}
  }
}

===

{
  "AddSystem": {
    "systemId": 30002187,
    "isPinned": true,
    "displayData": {"Manual": {"x": 90, "y": 40}},
    "stance": "Unknown"
  }
}

===

{
  "AddSystem": {
    "systemId": 30002659,
    "isPinned": true,
    "displayData": {"Manual": {"x": 90, "y": 200}},
    "stance": "Unknown"
  }
}

===

{
  "AddSystem": {
    "systemId": 30002510,
    "isPinned": true,
    "displayData": {"Manual": {"x": 90, "y": 240}},
    "stance": "Unknown"
  }
}

===

{
  "AddSystem": {
    "systemId": 31002558,
    "name": {
      "Name": {
        "value": "ABC-12"
      }
    },
    "isPinned": true,
    "displayData": {"Manual": {"x": 240, "y": 240}},
    "stance": "Friendly"
  }
}

===

{
  "AddSystemConnection": {
    "fromSystemId": 30002510,
    "toSystemId": 31002558
  }
}


###

