## Reference requests
##
## These endpoints return "static" data and do not require authentication
###

# @name GetRefSolarSystem
GET {{api}}/reference/system/Rens

###

# Used by the client to pre-load static reference data (to avoid balooning request sizes)
# @name GetRefAll
GET {{api}}/reference/all

###

# Used by the client to pre-load solar systems (to avoid doing that request every time)
# @name GetRefSolarSystemsAll
GET {{api}}/reference/all/systems

###

# @name GetRefFactions
GET {{api}}/reference/factions

###

# @name GetRefShipTypes
GET {{api}}/reference/shipTypes

###

# @name GetRefStarTypes
GET {{api}}/reference/starTypes

###

# @name GetRefStationOperations
GET {{api}}/reference/stationOperations

###

# @name GetRefWormholeTypes
GET {{api}}/reference/wormholeTypes

###