# prod-like configuration, designed to be stored inside a secret file (and not using any environment overrides)
include "application.conf"

control-tower {
  auth {
    secret: "CHANGEME"
    esi-callback-secret: "CHANGEME"
    encryption-secret: "CHANGEME"
    esi {
      client-id: "CHANGEME"
      client-secret: "CHANGEME"
    }
  }
  db: "/app/db"
  http {
    protocol: "https"
    host: "your.fqdn.here" # CHANGEME
  }
}
